### ISSUE TITLE
is it possible to randomize location of spawned units to make them a little harder to predict where they'll spawn? 

### ISSUE THREAD

**Issue by Leafback** [CapnFruitloops/ARCOMM-DCS#2]
basically, spawn X at Sochi, but X could be in one of several locations at Sochi. I suspect there's a limitation against this in DCS though.

**Comment by ChickenSim** [comment]
I think they already spawn in randomized, we may just need to expand the radius or something. If you spawn multiple groups in, they tend to appear pseudo-randomly around the same general area

**Comment by PeachMKVIII** [comment]
Radius expanded in the Syria mission. Can test with that mission to see. Will update Caucasus map shortly.

**Comment by PeachMKVIII** [comment]
@CapnFruitloops I updated the current rotation maps with larger spawn zones.
